version: "3"

services:
   backend:
      build: ./
      command: poetry run python3 server.py
      restart: always
      networks:
         - default
      ports:
         - "5000:5000"
      depends_on:
         - database
   database:
      build: database/
      networks:
         - default

